### ISSUE TITLE
Transaction ID is missing

### ISSUE THREAD

**Issue by hakmeh** [paytabscom/paytabs-opencart3.x#2]
Dears,
I made a purchase on my website (opencart 3.0.3.3), the money was deducted from my account, the amount was successfully debited in my paytabs account, but there was an issue with the order and it did not get created on my site as shown below
=======================================================================
![error](https://user-images.githubusercontent.com/36436325/91667017-3f27e180-eb0a-11ea-8ead-626061b84575.png)
=======================================================================

**Comment by wajihkm** [comment]
Hi @hakmeh 
Could you please tell us which plugin version you are using?
How often this issue is happen?

(This issue could happen if your website is not secured with SSL)

Thanks

**Comment by hakmeh** [comment]
Dear Wajihkm
the first test was using the files which I downloaded it from the download button and install it using FTP
the second test I was using 1.5.0 release (ocmod version) and yet it is the same result

**Comment by wajihkm** [comment]
Hi @hakmeh 
Could you please send an email to
customercare@paytabs.com

So the team will arrange a session with you to investigate this issue.

Thanks

**Comment by hakmeh** [comment]
I already have opened a ticket 2 days ago but still nothing useful, even a late reply...

**Comment by wajihkm** [comment]
Very sorry to hear that,
Will check and get back to you soon
